/**
 * Arithmetic in GF(256), the field QR error correction is defined over.
 *
 * ISO/IEC 18004 section 8.5.1: the field is generated by the primitive
 * polynomial x^8 + x^4 + x^3 + x^2 + 1 (0x11D), with 2 as the generator
 * element. Every value below follows from those two choices.
 *
 * Per ADR-0012 this file holds no QR tables -- it is pure field arithmetic and
 * knows nothing about versions, EC levels, or codewords.
 */

/** Primitive polynomial x^8 + x^4 + x^3 + x^2 + 1. */
export const PRIMITIVE_POLYNOMIAL = 0x11d;

/** Generator element of the multiplicative group. */
export const GENERATOR = 0x02;

/** Order of the multiplicative group: every nonzero element is 2^k for some k < 255. */
export const ORDER = 255;

const EXP = new Uint8Array(ORDER);
const LOG = new Uint8Array(256);

// Pure table construction at module load. No observable side effects, so this
// stays compatible with "sideEffects": false (AGENTS.md section 1).
{
  let value = 1;
  for (let power = 0; power < ORDER; power += 1) {
    EXP[power] = value;
    LOG[value] = power;
    value <<= 1;
    if (value & 0x100) value ^= PRIMITIVE_POLYNOMIAL;
  }
}

/**
 * 2^power in GF(256).
 *
 * @param {number} power exponent; reduced modulo 255, so any integer is valid
 * @returns {number} field element in 1..255
 */
export function exp(power) {
  return EXP[((power % ORDER) + ORDER) % ORDER];
}

/**
 * Discrete logarithm base 2.
 *
 * @param {number} value nonzero field element
 * @returns {number} k such that 2^k === value
 */
export function log(value) {
  return LOG[value];
}

/**
 * Field multiplication.
 *
 * @param {number} a field element
 * @param {number} b field element
 * @returns {number} a * b in GF(256)
 */
export function multiply(a, b) {
  if (a === 0 || b === 0) return 0;
  return EXP[(LOG[a] + LOG[b]) % ORDER];
}

/**
 * Field division.
 *
 * @param {number} a numerator
 * @param {number} b denominator; must be nonzero
 * @returns {number} a / b in GF(256)
 */
export function divide(a, b) {
  if (a === 0) return 0;
  return EXP[(LOG[a] - LOG[b] + ORDER) % ORDER];
}

/**
 * Multiplicative inverse.
 *
 * @param {number} a nonzero field element
 * @returns {number} a^-1 in GF(256)
 */
export function inverse(a) {
  return EXP[(ORDER - LOG[a]) % ORDER];
}
