/**
 * Writes the golden artefacts: matrix vectors and SVG snapshots.
 *
 * Every vector declares a `source`. Entries sourced from published material are
 * independent conformance evidence; entries marked `regression` only lock in
 * current behaviour. Mixing the two without labelling them is how a regression
 * snapshot gets mistaken for proof of conformance (ADR-0014).
 *
 * Usage: node scripts/gen-goldens.js
 */
import { writeFileSync } from 'node:fs';
import { qr, matrixToSvg } from '../src/index.js';
import { buildDataCodewords } from '../src/core/version.js';
import { makeSegments } from '../src/core/segment.js';
import { versionRangeIndex } from '../src/core/mode.js';

/** Cases locked in as regression baselines. */
const REGRESSION_CASES = [
  { name: 'hello-world-1m', data: 'HELLO WORLD', ecLevel: 'M' },
  { name: 'hello-world-1q-mask6', data: 'HELLO WORLD', ecLevel: 'Q' },
  { name: 'numeric-01234567-1l', data: '01234567', ecLevel: 'L' },
  { name: 'url-lowercase-2m', data: 'https://example.com', ecLevel: 'M' },
  { name: 'non-ascii-eci-1m', data: 'café', ecLevel: 'M' },
  { name: 'empty-1h', data: '', ecLevel: 'H' },
  { name: 'forced-mask-0', data: 'MASK ZERO', ecLevel: 'M', mask: 0 },
  // Version boundaries that change the symbol's structure or its indicator
  // widths, per the coverage matrix in AGENTS.md section 6.
  { name: 'version-6-no-version-info', data: 'V6', ecLevel: 'M', version: 6 },
  { name: 'version-7-has-version-info', data: 'V7', ecLevel: 'M', version: 7 },
  { name: 'version-9-narrow-count', data: 'V9 COUNT WIDTH', ecLevel: 'M', version: 9 },
  { name: 'version-10-wider-count', data: 'V10 COUNT WIDTH', ecLevel: 'M', version: 10 },
  { name: 'version-26-mid-count', data: 'V26 COUNT WIDTH', ecLevel: 'M', version: 26 },
  { name: 'version-27-widest-count', data: 'V27 COUNT WIDTH', ecLevel: 'M', version: 27 },
  { name: 'version-40-maximum', data: 'V40 MAXIMUM', ecLevel: 'L', version: 40 },
];

/** Rows as run-length-free binary strings: compact, and diffable by eye. */
function rowsOf(matrix) {
  const rows = [];
  for (let row = 0; row < matrix.size; row += 1) {
    let line = '';
    for (let col = 0; col < matrix.size; col += 1) line += matrix.get(row, col) ? '1' : '0';
    rows.push(line);
  }
  return rows;
}

const hex = (bytes) => Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join(' ');

/** @returns {object} the full vectors document */
export function buildVectors() {
  const vectors = [];

  // --- Published conformance vectors -------------------------------------
  // Data codewords for "HELLO WORLD" at version 1, worked through in the
  // ISO/IEC 18004 alphanumeric example and reproduced in the widely used
  // tutorials. Independent of this implementation.
  for (const [ecLevel, expected] of [
    ['M', '20 5b 0b 78 d1 72 dc 4d 43 40 ec 11 ec 11 ec 11'],
    ['Q', '20 5b 0b 78 d1 72 dc 4d 43 40 ec 11 ec'],
  ]) {
    const segments = makeSegments('HELLO WORLD', { rangeIndex: versionRangeIndex(1) });
    const actual = hex(buildDataCodewords({ segments, version: 1, ecLevel }));
    if (actual !== expected) {
      throw new Error(`published vector mismatch for 1-${ecLevel}: ${actual}`);
    }
    vectors.push({
      name: `published-hello-world-1${ecLevel.toLowerCase()}-codewords`,
      source: 'published',
      note: 'ISO/IEC 18004 alphanumeric worked example',
      data: 'HELLO WORLD',
      ecLevel,
      version: 1,
      dataCodewordsHex: expected,
    });
  }

  // --- Regression baselines ---------------------------------------------
  for (const testCase of REGRESSION_CASES) {
    const { data, ...options } = testCase;
    const result = qr(data, options);
    vectors.push({
      name: testCase.name,
      source: 'regression',
      note: 'locks in current output; not independent conformance evidence',
      data,
      ecLevel: result.ecLevel,
      version: result.version,
      mask: result.mask,
      size: result.size,
      eci: result.eci ?? null,
      rows: rowsOf(result.matrix),
    });
  }

  return {
    $comment: 'Generated by scripts/gen-goldens.js. Append-only per ADR-0008; '
      + 'every entry declares its source per ADR-0014.',
    vectors,
  };
}

/** SVG snapshots, one per rendering shape. */
const SVG_CASES = [
  { name: 'square', data: 'HELLO WORLD', options: { ecLevel: 'M', scale: 4 } },
  { name: 'dot', data: 'HELLO WORLD', options: { ecLevel: 'M', scale: 4, shape: 'dot' } },
  { name: 'rounded', data: 'HELLO WORLD', options: { ecLevel: 'M', scale: 4, shape: 'rounded' } },
  { name: 'coloured', data: 'HELLO WORLD', options: { ecLevel: 'M', scale: 8, dark: '#1a1a2e', light: '#eaeaea' } },
  { name: 'tight-quiet-zone', data: 'HELLO WORLD', options: { ecLevel: 'M', scale: 4, quietZone: 0 } },
];

/** @returns {Array<{name: string, svg: string}>} rendered snapshots */
export function buildSvgSnapshots() {
  return SVG_CASES.map(({ name, data, options }) => {
    const { matrix } = qr(data, options);
    return {
      name,
      svg: matrixToSvg(matrix, {
        scale: options.scale,
        quietZone: options.quietZone ?? 4,
        dark: options.dark ?? '#000000',
        light: options.light ?? '#ffffff',
        shape: options.shape ?? 'square',
      }),
    };
  });
}

export const VECTORS_PATH = new URL('../test/golden/vectors.json', import.meta.url);
export const svgPath = (name) => new URL(`../test/golden/svg-${name}.svg`, import.meta.url);

if (process.argv[1]?.endsWith('gen-goldens.js')) {
  writeFileSync(VECTORS_PATH, `${JSON.stringify(buildVectors(), null, 2)}\n`);
  console.log('wrote test/golden/vectors.json');
  for (const { name, svg } of buildSvgSnapshots()) {
    writeFileSync(svgPath(name), `${svg}\n`);
    console.log(`wrote test/golden/svg-${name}.svg`);
  }
}
