/**
 * Generates `src/core/constants.js`.
 *
 * ADR-0007: spec tables are generated by this script and the output is
 * committed. CI re-runs this and fails on a dirty diff, so the shipped file is
 * provably what this script produces.
 *
 * Design goal: transcribe as little as possible. Only two tables in ISO/IEC
 * 18004 are genuinely irreducible -- error-correction codewords per block, and
 * block count, both per version and EC level (Table 9). Everything else here is
 * derived from structural rules, so a transcription slip has a much smaller
 * surface to hide in.
 *
 * Usage: node scripts/gen-tables.js
 *
 * `buildConstants()` is exported so a test can regenerate in memory and compare
 * against the committed file, which checks the same property as the CI
 * `git diff` gate but without depending on git state.
 */
import { writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const MIN_VERSION = 1;
const MAX_VERSION = 40;
const LEVELS = ['L', 'M', 'Q', 'H'];

// ---------------------------------------------------------------------------
// Transcribed tables -- ISO/IEC 18004 Table 9, indexed [version - 1].
// These are the only hand-entered numbers in this file.
// ---------------------------------------------------------------------------

/** Error-correction codewords per block. */
const ECC_PER_BLOCK = {
  L: [7, 10, 15, 20, 26, 18, 20, 24, 30, 18, 20, 24, 26, 30, 22, 24, 28, 30, 28, 28,
    28, 28, 30, 30, 26, 28, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
  M: [10, 16, 26, 18, 24, 16, 18, 22, 22, 26, 30, 22, 22, 24, 24, 28, 28, 26, 26, 26,
    26, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28],
  Q: [13, 22, 18, 26, 18, 24, 18, 22, 20, 24, 28, 26, 24, 20, 30, 24, 28, 28, 26, 30,
    28, 30, 30, 30, 30, 28, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
  H: [17, 28, 22, 16, 22, 28, 26, 26, 24, 28, 24, 28, 22, 24, 24, 30, 28, 28, 26, 28,
    30, 24, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
};

/** Number of error-correction blocks. */
const EC_BLOCKS = {
  L: [1, 1, 1, 1, 1, 2, 2, 2, 2, 4, 4, 4, 4, 4, 6, 6, 6, 6, 7, 8,
    8, 9, 9, 10, 12, 12, 12, 13, 14, 15, 16, 17, 18, 19, 19, 20, 21, 22, 24, 25],
  M: [1, 1, 1, 2, 2, 4, 4, 4, 5, 5, 5, 8, 9, 9, 10, 10, 11, 13, 14, 16,
    17, 17, 18, 20, 21, 23, 25, 26, 28, 29, 31, 33, 35, 37, 38, 40, 43, 45, 47, 49],
  Q: [1, 1, 2, 2, 4, 4, 6, 6, 8, 8, 8, 10, 12, 16, 12, 17, 16, 18, 21, 20,
    23, 23, 25, 27, 29, 34, 34, 35, 38, 40, 43, 45, 48, 51, 53, 56, 59, 62, 65, 68],
  H: [1, 1, 2, 4, 4, 4, 5, 6, 8, 8, 11, 11, 16, 16, 18, 16, 19, 21, 25, 25,
    25, 34, 30, 32, 35, 37, 40, 42, 45, 48, 51, 54, 57, 60, 63, 66, 70, 74, 77, 81],
};

// ---------------------------------------------------------------------------
// Derived tables
// ---------------------------------------------------------------------------

/** Module count along one side. ISO/IEC 18004 section 6.5.1. */
const sizeForVersion = (version) => version * 4 + 17;

/** Number of alignment patterns along one axis. */
const alignmentCount = (version) => (version === 1 ? 0 : Math.floor(version / 7) + 2);

/**
 * Raw data-module count: total modules minus every function pattern.
 *
 * Derived rather than transcribed. The closed form below is the standard
 * reduction of "size^2, less three 8x8 finder-plus-separator regions, less the
 * two timing patterns, less format information, less alignment patterns, less
 * version information for v >= 7".
 */
function rawDataModules(version) {
  let modules = (16 * version + 128) * version + 64;
  const numAlign = alignmentCount(version);
  if (numAlign > 0) {
    // Alignment patterns, discounting the three that overlap finder patterns
    // and the parts that overlap the timing patterns.
    modules -= (25 * numAlign - 10) * numAlign - 55;
    if (version >= 7) modules -= 36; // two copies of 18-bit version information
  }
  return modules;
}

/** Total codewords available at a version, data and error correction combined. */
const totalCodewords = (version) => Math.floor(rawDataModules(version) / 8);

/**
 * Alignment pattern centre coordinates. ISO/IEC 18004 Annex E.
 *
 * Version 32 is the documented irregularity -- its spacing does not follow the
 * general rule, so it is special-cased rather than fudged.
 */
function alignmentCentres(version) {
  if (version === 1) return [];
  const count = alignmentCount(version);
  const step = version === 32 ? 26 : Math.ceil((version * 4 + 4) / (count * 2 - 2)) * 2;
  const centres = [6];
  for (let pos = sizeForVersion(version) - 7; centres.length < count; pos -= step) {
    centres.splice(1, 0, pos);
  }
  return centres;
}

/** Data codewords available at a version and EC level. */
function dataCodewords(version, level) {
  const blocks = EC_BLOCKS[level][version - 1];
  const eccPerBlock = ECC_PER_BLOCK[level][version - 1];
  return totalCodewords(version) - blocks * eccPerBlock;
}

// ---------------------------------------------------------------------------
// Emit
// ---------------------------------------------------------------------------

/** Renders `values` as a wrapped array literal body, indented by `indent`. */
function arrayLiteral(values, indent, perLine = 20) {
  const lines = [];
  for (let i = 0; i < values.length; i += perLine) {
    lines.push(indent + values.slice(i, i + perLine).join(', ') + ',');
  }
  return lines.join('\n');
}

function levelTable(name, byLevel, comment) {
  const body = LEVELS.map((level) => `  ${level}: [\n${arrayLiteral(byLevel[level], '    ')}\n  ],`).join('\n');
  return `/**\n * ${comment}\n *\n * Indexed \`[level][version - 1]\`.\n */\nexport const ${name} = Object.freeze({\n${body}\n});\n`;
}

const versions = Array.from({ length: MAX_VERSION }, (_, i) => i + 1);

const derivedDataCodewords = {};
for (const level of LEVELS) {
  derivedDataCodewords[level] = versions.map((v) => dataCodewords(v, level));
}

/** Builds the full text of `src/core/constants.js`. */
export function buildConstants() {
const out = `/**
 * GENERATED FILE -- DO NOT EDIT BY HAND.
 *
 * Produced by \`scripts/gen-tables.js\` (ADR-0007). Edits here are overwritten
 * on the next \`npm run gen:tables\`, and CI fails if this file does not match
 * what the generator produces.
 *
 * Source: ISO/IEC 18004 -- Table 9 (error correction characteristics),
 * section 6.5.1 (symbol size), Annex E (alignment pattern positions).
 *
 * Per ADR-0012 this file holds version-indexed tables only. Mode-specific
 * constants live with their encoder in \`src/encode/\`.
 */

/** Smallest QR symbol version. */
export const MIN_VERSION = ${MIN_VERSION};

/** Largest QR symbol version. */
export const MAX_VERSION = ${MAX_VERSION};

/** Error-correction levels, weakest to strongest recovery. */
export const ECLevel = Object.freeze({
  L: 'L',
  M: 'M',
  Q: 'Q',
  H: 'H',
});

/** Error-correction levels in ascending order of recovery capacity. */
export const EC_LEVELS = Object.freeze(['L', 'M', 'Q', 'H']);

/**
 * Approximate recovery capacity per level, as a fraction of codewords.
 * Informational -- used for logo-overlay budgeting, never for encoding.
 */
export const EC_RECOVERY = Object.freeze({
  L: 0.07,
  M: 0.15,
  Q: 0.25,
  H: 0.30,
});

/**
 * Two-bit level indicator used in the format information field.
 *
 * NOT in level order -- L is 01 and M is 00. ISO/IEC 18004 Table 12.
 * Deriving these from an ordered level list is a known way to ship codes that
 * scan on lenient readers and fail on strict ones.
 */
export const EC_FORMAT_BITS = Object.freeze({
  L: 0b01,
  M: 0b00,
  Q: 0b11,
  H: 0b10,
});

/**
 * Total codewords per version, data and error correction combined.
 *
 * Indexed by version; index 0 is unused and holds 0.
 */
export const TOTAL_CODEWORDS = Object.freeze([
  0,
${arrayLiteral(versions.map(totalCodewords), '  ')}
]);

${levelTable('ECC_PER_BLOCK', ECC_PER_BLOCK, 'Error-correction codewords per block.')}
${levelTable('EC_BLOCKS', EC_BLOCKS, 'Number of error-correction blocks.')}
${levelTable('DATA_CODEWORDS', derivedDataCodewords, 'Data codewords available, derived from TOTAL_CODEWORDS less error correction.')}
/**
 * Alignment pattern centre coordinates per version, ascending.
 *
 * Indexed by version; index 0 is unused and holds an empty array. Version 1 has
 * no alignment patterns.
 */
export const ALIGNMENT_CENTRES = Object.freeze([
  [],
${versions.map((v) => `  [${alignmentCentres(v).join(', ')}],`).join('\n')}
]);

/** Module count along one side of a symbol at the given version. */
export function sizeForVersion(version) {
  return version * 4 + 17;
}
`;

return out;
}

/** Absolute location of the generated file. */
export const CONSTANTS_PATH = new URL('../src/core/constants.js', import.meta.url);

const invokedDirectly = process.argv[1] !== undefined
  && import.meta.url === pathToFileURL(process.argv[1]).href;

if (invokedDirectly) {
  writeFileSync(CONSTANTS_PATH, buildConstants());
  console.log(`gen-tables: wrote ${MAX_VERSION} versions x ${LEVELS.length} levels to src/core/constants.js`);
}
